export const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
export const POST_UPDATE_SINGLE_SUCCESS = 'POST_UPDATE_SINGLE_SUCCESS';
export const POST_DELETE_SINGLE_SUCCESS = 'POST_DELETE_SINGLE_SUCCESS';
// export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';
